import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Base App Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-center text-xl font-bold">Base Next.js + Tailwind Project</h1>
      </main>
    </div>
  )
}
